from WebScraper.RSS_Scraper import rss_scraper

lemonde_list = [
    "https://www.lemonde.fr/rss/une.xml",
    "https://www.lemonde.fr/international/rss_full.xml",
    "https://www.lemonde.fr/europe/rss_full.xml",
    "https://www.lemonde.fr/ameriques/rss_full.xml",
    "https://www.lemonde.fr/afrique/rss_full.xml",
    "https://www.lemonde.fr/asie-pacifique/rss_full.xml",
    "https://www.lemonde.fr/proche-orient/rss_full.xml",
    "https://www.lemonde.fr/royaume-uni/rss_full.xml",
    "https://www.lemonde.fr/etats-unis/rss_full.xml",
    "https://www.lemonde.fr/politique/rss_full.xml",
    "https://www.lemonde.fr/societe/rss_full.xml",
    "https://www.lemonde.fr/les-decodeurs/rss_full.xml",
    "https://www.lemonde.fr/justice/rss_full.xml",
    "https://www.lemonde.fr/police/rss_full.xml",
    "https://www.lemonde.fr/campus/rss_full.xml",
    "https://www.lemonde.fr/education/rss_full.xml",
    "https://www.lemonde.fr/culture/rss_full.xml",
    "https://www.lemonde.fr/cinema/rss_full.xml",
    "https://www.lemonde.fr/musiques/rss_full.xml",
    "https://www.lemonde.fr/televisions-radio/rss_full.xml",
    "https://www.lemonde.fr/livres/rss_full.xml",
    "https://www.lemonde.fr/arts/rss_full.xml",
    "https://www.lemonde.fr/scenes/rss_full.xml",
    "https://www.lemonde.fr/sport/rss_full.xml",
    "https://www.lemonde.fr/football/rss_full.xml",
    "https://www.lemonde.fr/rugby/rss_full.xml",
    "https://www.lemonde.fr/tennis/rss_full.xml",
    "https://www.lemonde.fr/cyclisme/rss_full.xml",
    "https://www.lemonde.fr/basket/rss_full.xml",
    "https://www.lemonde.fr/planete/rss_full.xml",
    "https://www.lemonde.fr/climat/rss_full.xml",
    "https://www.lemonde.fr/agriculture/rss_full.xml",
    "https://www.lemonde.fr/afrique-climat-et-environnement/rss_full.xml",
    "https://www.lemonde.fr/pixels/rss_full.xml",
    "https://www.lemonde.fr/jeux-video/rss_full.xml",
    "https://www.lemonde.fr/cultures-web/rss_full.xml",
    "https://www.lemonde.fr/sciences/rss_full.xml",
    "https://www.lemonde.fr/espace/rss_full.xml",
    "https://www.lemonde.fr/biologie/rss_full.xml",
    "https://www.lemonde.fr/medecine/rss_full.xml",
    "https://www.lemonde.fr/physique/rss_full.xml",
    "https://www.lemonde.fr/sante/rss_full.xml",
    "https://www.lemonde.fr/idees/rss_full.xml",
    "https://www.lemonde.fr/editoriaux/rss_full.xml",
    "https://www.lemonde.fr/chroniques/rss_full.xml",
    #"https://www.lemonde.fr/tribunes/rss_full.xml",
    "https://www.lemonde.fr/m-le-mag/rss_full.xml",
    "https://www.lemonde.fr/m-perso/rss_full.xml",
    "https://www.lemonde.fr/m-styles/rss_full.xml",
    "https://www.lemonde.fr/gastronomie/rss_full.xml",
    "https://www.lemonde.fr/les-recettes-du-monde/rss_full.xml",
    "https://www.lemonde.fr/sexo/rss_full.xml",
    "https://www.lemonde.fr/guides-d-achat/rss_full.xml",


]

url_list = [
    "https://www.francetvinfo.fr/titres.rss",
    "https://www.lemonde.fr/rss/une.xml",
    "https://www.bfmtv.com/rss/news-24-7/",
    "https://www.01net.com/actualites/feed/",
    "https://www.europe1.fr/rss.xml",
    "https://www.ouest-france.fr/rss/une",
    "https://dwh.lequipe.fr/api/edito/rss?path=/",
    "https://www.leprogres.fr/rss",
    "https://www.jeuxvideo.com/rss/rss.xml",
    "https://www.jeuxvideo.com/rss/rss-news.xml"
]

rss_getter = rss_scraper(url_list,'http://127.0.0.1:3000/articles')
rss_getter.get_articles()
