---
version: '3.8'

services:

  web:
    build: '.'
    ports:
      - '5000:5000'
    networks:
      - identinet
    depends_on:
      cassandra1:
        condition: service_healthy

  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper
    networks:
      - identinet

  kafka-1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: true
    networks:
      - identinet

  cassandra1:
      hostname: cassandra1
      image: cassandra:4
      ports:
        - 7000:7000
        - 9042:9042
      environment:
        - CASSANDRA_SEEDS=cassandra1
        - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      networks:
        - identinet
      depends_on:
        - kafka-1
      healthcheck:
        test: [ "CMD", "cqlsh" ]
        interval: 15s
        timeout: 10s
        retries: 10

networks:
  identinet:
    driver: bridge